- package.json
- readme.md
Only include `dist` directory when publishing to NPM
> fix: only include dist directory when publishing

- readme.md
- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput.test.tsx
- src/components/__tests__/__snapshots__/CurrencyInput.test.tsx.snap
- src/components/types.ts
- src/examples/Example1.tsx
- src/examples/Example2.tsx
Allow `name` as prop to be passed down to component, and in return will be the second param in the `onChange` callback.
> feat: allow name to be added to prop and onChange callback

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .releaserc.yml
cache `node_modules` to speed up workflow.
> chore: cache node_modules in build workflow

- readme.md
- src/components/CurrencyInput.tsx
- src/components/CurrencyInputProps.ts
- src/components/__tests__/CurrencyInput.test.tsx
Allow `disabled` prop to be passed down.
Issue #30
> feat: allow input to be disabled

- package.json
Previous master build failed because I had once accidentally published v1.0.0 on NPM and cannot remove. So need to trigger another build to update to next version.
> fix: artificial change to trigger version update

- README.md
- src/components/CurrencyInput.tsx
- src/components/CurrencyInputProps.ts
- src/components/__tests__/CurrencyInput.test.tsx
- src/components/utils/__tests__/cleanValue.spec.ts
- src/components/utils/cleanValue.ts
Added new prop `allowNegativeValue` so you can disable user from entering a negative value.
Issue: #66
> feat: add prop to disallow negative value

- src/components/CurrencyInput.tsx
Fixed a bug to with clearing the field through `value` prop.
Addresses #68
> fix: can clear field programmatically

- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput.test.tsx
Found a bug where `0` was not being prefixed.
> fix: prefix 0 value

- src/components/CurrencyInput.tsx
- src/components/utils/__tests__/cleanValue.spec.ts
- src/components/utils/cleanValue.ts
It should now better handle values before the prefix, and cursor should not jump around if you input values proceeding another value.
Issue #78
> fix: handle values before prefix

- .github/workflows/examples.yml
- .gitignore
- package.json
- src/components/CurrencyInput.tsx
- webpack.config.js
- webpack/webpack-base.config.js
- webpack/webpack-dev.config.js
- webpack/webpack-prod.config.js
Splitting the webpack configs to production and dev so they are easier to manage.
> refactor: split out webpack configs

- README.md
- src/components/CurrencyInput.tsx
- src/components/CurrencyInputProps.ts
- src/components/__tests__/CurrencyInput-abbreviated.spec.tsx
- src/components/__tests__/CurrencyInput-decimals.spec.tsx
- src/components/__tests__/CurrencyInput-handleKeyDown.spec.tsx
- src/components/__tests__/CurrencyInput-intl-config.spec.tsx
- src/components/__tests__/CurrencyInput-maxLength.spec.tsx
- src/components/__tests__/CurrencyInput-negative.spec.tsx
- src/components/__tests__/CurrencyInput-onBlurValue.spec.tsx
- src/components/__tests__/CurrencyInput-separators.spec.tsx
- src/components/__tests__/CurrencyInput.spec.tsx
- src/examples/Example1.tsx
- src/examples/Example2.tsx
- src/examples/Example3.tsx
This is quite a big change, but I feel that it is more "correct" because it allows the user to access original onChange event
Breaking Change: Renamed "onChange" to "onValueChange"
> feat: renamed onChange prop to onValueChange

- .enzymerc.js
- package.json
- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput-abbreviated.spec.tsx
- src/components/__tests__/CurrencyInput-decimals.spec.tsx
- src/components/__tests__/CurrencyInput-fixedDecimalLength.spec.tsx
- src/components/__tests__/CurrencyInput-handleKeyDown.spec.tsx
- src/components/__tests__/CurrencyInput-intl-config.spec.tsx
- src/components/__tests__/CurrencyInput-maxLength.spec.tsx
- src/components/__tests__/CurrencyInput-negative.spec.tsx
- src/components/__tests__/CurrencyInput-no-locale.spec.tsx
- src/components/__tests__/CurrencyInput-onBlur.spec.tsx
- src/components/__tests__/CurrencyInput-precision.spec.tsx
- src/components/__tests__/CurrencyInput-separators.spec.tsx
- src/components/__tests__/CurrencyInput.spec.tsx
- src/components/__tests__/__snapshots__/CurrencyInput.spec.tsx.snap
- src/components/utils/__tests__/formatValue.spec.ts
- src/components/utils/formatValue.ts
- yarn.lock
Switch to using `react-testing-library` instead of `enzyme`.
This is an improvement in the way the tests are written and simulates user typing events better, and has already caught a few bugs.
> test: replace enzyme with react testing library

- package.json
- src/components/CurrencyInput.tsx
- src/components/CurrencyInputProps.ts
- src/components/__tests__/CurrencyInput-customInput.spec.tsx
- src/examples/Example3.tsx
Allow `customInput` prop.
Issue: #111
Will need to do some testing after merge and release.
> feat: allow customInput prop

- src/components/__tests__/CurrencyInput.spec.tsx
- src/components/utils/__tests__/formatValue.spec.ts
- src/components/utils/formatValue.ts
Fixes initial rendering if value has decimals and decimal scale eg. `<CurrencyInput value={0.1} decimalScale={2} />`
> fix: default value with decimal scale renders correctly part 2

- src/components/CurrencyInputProps.ts
- src/components/utils/__tests__/formatValue.spec.ts
- src/components/utils/__tests__/getLocaleConfig.spec.ts
- src/components/utils/cleanValue.ts
- src/components/utils/formatValue.ts
- src/components/utils/getLocaleConfig.ts
`intlConfig` option `currency` can be optional, so formatting can still happen without currency symbol.
Issue: #129
> fix: intl config currency is optional

- src/components/CurrencyInput.tsx
Prevent cursor moving if only "-" value, and prevents accidentally entering "1-" at the beginning, which parses to "1" (incorrect).
Issue: #131
> fix: prevent cursor moving if only negative value at start

- src/components/utils/__tests__/cleanValue.spec.ts
- src/components/utils/cleanValue.ts
Removes prefix correctly if prefix is letters only.
Issue: #136
> fix: remove prefix if letters

- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput-intl-config.spec.tsx
- src/components/utils/__tests__/cleanValue.spec.ts
- src/components/utils/__tests__/formatValue.spec.ts
- src/components/utils/__tests__/getLocaleConfig.spec.ts
- src/components/utils/cleanValue.ts
- src/components/utils/formatValue.ts
- src/components/utils/getLocaleConfig.ts
- src/examples/Example1.tsx
Fix bug when intl config specifies a prefix and user enters a negative value.
Issue: #146
> fix: handle intl config with prefix and negative

- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput-backspace.spec.tsx
Prevent cursor from jumping to the end when delete key pressed.
Issue: #153
> fix: prevent cursor jumping when press delete key

- src/components/utils/__tests__/parseAbbrValue.spec.ts
- src/components/utils/parseAbbrValue.ts
Noticed a bug when entering an abbreviation after period eg. '1.k'
> fix: abbreviation char after period

- src/components/CurrencyInput.tsx
- src/components/CurrencyInputProps.ts
- src/components/__tests__/CurrencyInput-abbreviated.spec.tsx
- src/components/__tests__/CurrencyInput-backspace.spec.tsx
- src/components/__tests__/CurrencyInput-decimals.spec.tsx
- src/components/__tests__/CurrencyInput-fixedDecimalLength.spec.tsx
- src/components/__tests__/CurrencyInput-handleKeyDown.spec.tsx
- src/components/__tests__/CurrencyInput-intl-config.spec.tsx
- src/components/__tests__/CurrencyInput-maxLength.spec.tsx
- src/components/__tests__/CurrencyInput-negative.spec.tsx
- src/components/__tests__/CurrencyInput-onBlur.spec.tsx
- src/components/__tests__/CurrencyInput-precision.spec.tsx
- src/components/__tests__/CurrencyInput-separators.spec.tsx
- src/components/__tests__/CurrencyInput.spec.tsx
`onValueChange` callback can accept a third param for `Values` object, which will contain `{ float, formatted, value }`
> feat: onValueChange calls Values object as third param

- package.json
The package was shipping source maps in `dist` pointing to paths like `../src/components`, so Webpack threw a warning when it couldn't find them.
This PR ships the source code in the package so source maps don't point to nothing. One other solution would be not to use source maps, but this one is probably nicer for DX :)
Fixes #210
> Fix Webpack 5 warnings with Create React App

- src/components/CurrencyInput.tsx
- src/components/CurrencyInputProps.ts
- src/components/__tests__/CurrencyInput-backspace.spec.tsx
- src/components/utils/formatValue.ts
- src/components/utils/index.ts
- src/components/utils/repositionCursor.ts
- src/examples/Example1.tsx
- yarn.lock
ref #211 
When removing numbers around group and decimal separators, the cursor jumps around. This PR fixes that.
* if the cursor is to the right of a group separator and the user presses backspace, the number to the left of the separator will be deleted and the cursor will remain to the right of the preceding character
* if the cursor is to the left of a group separator and the user presses delete, the number to the right of the separator will be deleted and the cursor will remain to the left of the next character
* if the user deletes characters from in between an input back to the prefix, if they press backspace again, the cursor will remain to the right of the prefix.
> Fix inconsistent cursor behaviour

- src/components/utils/__tests__/formatValue.spec.ts
- src/components/utils/formatValue.ts
Having the following configuration options:
- value: `123.00`
- decimalScale: `2`
- provide intlConfig, but without specifying the currency, e.g., just `{ locale: "en-US" }`
We'd expect `123.00` but receive `123`
Now it's fixed 😄
> fix: no decimals if defined decimalScale, input value as  X.00 and intlConfig, but without no currency

- src/components/CurrencyInput.tsx
In the following scenario:
- On the master branch
- Using Safari on MacOS
- Having set `decimalScale={2}` for the component
Doing the following:
- Go to "Example 1" (make sure you have "Example 2" in the viewport to jump to another input later)
- Click on the input
- Insert "123"
- Place your cursor on "Example 2" input and click
- **Notice that the cursor gets stuck and you need to click again to focus on the example 2 input**
I was implementing a regular form with this input and it gets stuck in this specific case which would be annoying for the users.
> fix: safari cursor stuck if onBlur & decimalScale set

- package.json
- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput-decimals.spec.tsx
* Replace the decimal separator from value only when the former is not an empty string.  Otherwise, `'1'.replace('', '.')` returns `.1`.
* Allow tests to be run from machines which have different locales. The reason is that Intl.NumberFormat constructor falls back to the machine's LANG.
> fix: parse float for currencies w/o decimal sep

- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput.spec.tsx
- src/components/utils/__tests__/cleanValue.spec.ts
- src/components/utils/cleanValue.ts
Fixes https://github.com/cchanxzy/react-currency-input-field/issues/293, https://github.com/cchanxzy/react-currency-input-field/issues/286, and single decimal point inputs. See original issues for how to reproduce.
Single decimal point repro:
1. In [Example 1](https://cchanxzy.github.io/react-currency-input-field/), type `.` (can be reproduced in any other input that accepts `.` or `,` decimal separators, e.g. Example 3 with `,` input);
2. Move focus outside input;
3. Results in `"formatted": "£NaN.", "value": "."` values;
4. Expected `"formatted": "", "value": ""`;
> Fix decimal separator issues

- src/components/utils/__tests__/fixedDecimalValue.spec.ts
- src/components/utils/fixedDecimalValue.ts
Fixes issue #292 regarding `fixedDecimalValue`.
Also, fixes/better handles if `fixedDecimalValue = 0` . Prior to this fix, `0` would be ignored, which isn't exactly correct.
> fix: fixedDecimalValue issue #292 and handle fixedDecimalValue 0

- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput.spec.tsx
Fixes #322.
I'm unsure if that's the correct approach, but all tests pass, including the ones I added that weren't passing before the fix.
> fix: Update input to empty string when `userValue` is `undefined`

- src/components/utils/__tests__/formatValue.spec.ts
- src/components/utils/formatValue.ts
Issue https://github.com/cchanxzy/react-currency-input-field/issues/299
- This fix is specifically targeted to handle decimal input when ' . ' is entered. 
- Added neccessary tests.
- Tests are passing locally.
Built and tested.
> Issue #299 : Handle decimal values starting with ' . '

- src/components/CurrencyInput.tsx
- src/components/CurrencyInputProps.ts
- src/components/__tests__/CurrencyInput-onBlur.spec.tsx
This pull request introduces the formatValueOnBlur flag, allowing users to customize the behavior of the onValueChange function on blur events. The default behavior is set to true, ensuring no disruption to the current production code.
> Enhancement: Introduce formatValueOnBlur Flag

- src/index.ts
We forgot to export the `IntlConfig` props, resulting longer code when importing this type:
```ts
import type { IntlConfig } from 'react-currency-input-field/dist/components/CurrencyInputProps'
```
This changes adjust it so that user will no longer import the types from deep folder
```ts
import CurrencyInput, { type IntlConfig } from 'react-currency-input-field'
```
> feat(types): export `IntlConfig` type from root entry point

- src/components/CurrencyInput.tsx
- src/components/__tests__/CurrencyInput-decimals.spec.tsx
- src/components/__tests__/CurrencyInput-handleKeyDown.spec.tsx
- src/components/utils/__tests__/padTrimValue.spec.ts
- src/components/utils/padTrimValue.ts
Previously, for zero-decimal currencies (such as JPY), input will be lost on blur if `decimalScale` is used (no matter what value was passed in). This was down to the fact that `decimalSeparator` from `getLocaleConfig` will be `undefined` (since it doesn't exist in the output of `formatToParts`), and the fallback value of `''` was used.
This PR adds handling in the pad/trim logic to skip all processing when we see `''` as the separator.
Re-opened since #379 was closed due to staleness.
Fixes #310
> fix: handle cases where decimalSeparator is empty

- src/components/CurrencyInputProps.ts
- src/components/utils/formatValue.ts
- src/components/utils/getLocaleConfig.ts
`intlConfig` currently only exposes `locale` and `currency`.
This PR adds full support for [`Intl.NumberFormatOptions`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat).
Fixes #253 
Passing `{ useGrouping: true }` fixes #356
> feat: intlConfig support all NumberFormatOptions

- README.md
- src/components/CurrencyInputProps.ts
- src/components/__tests__/CurrencyInput-intl-config.spec.tsx
- src/components/utils/__tests__/formatValue.spec.ts
- src/examples/Example3.tsx
It's been a while since I've updated the documentation, so this PR is to update the prop descriptions and give more examples so that it is easier to use.
Example of improved type definition documentation:
> docs: update README and improve type documentation

- .releaserc.yml
Adding `experimental` branch to semantic release settings so that I can test some build config changes without polluting main.
The `experimental` branch will be for testing purposes only.
> ci: add experimental branch to semantic release

- esbuild.mjs
This PR updates the build to emit single-file bundles for both ESM and CJS. It removes extensionless internal imports from the ESM output that break SSR under Node’s ESM resolver.
The published ESM entry `dist/esm/index.js` previously referenced internal files using extensionless relative imports (e.g., `./components/CurrencyInput`). When a dev SSR tool (e.g., Vite with React Router) externalizes the package, Node tries to resolve those imports directly and fails because Node ESM requires explicit file extensions.
This surfaced as: “Cannot find module .../dist/esm/components/CurrencyInput imported from .../dist/esm/index.js”.
- Switch to single-file bundles for both ESM and CJS:
- ESM: entryPoints: ['src/index.ts'], outfile: 'dist/esm/index.js', bundle: true, format: 'esm', platform: …
> fix(esm): bundle ESM/CJS builds to avoid Node ESM resolution issues in SSR
