cchanxzy/react-currency-input-field

.github/workflows/pr.yml

Attempting to use github actions

chore: trying ci process

---

.gitignore
readme.md
src/components/CurrencyInput.tsx
src/components/__tests__/CurrencyInput.test.tsx
src/components/__tests__/__snapshots__/CurrencyInput.test.tsx.snap
src/components/__tests__/utilities.spec.ts
src/components/types.ts
src/components/utilities.ts
src/example.html
src/examples/Example1.tsx
src/examples/Example2.tsx

New features:
- Can set default value
- Allows decimals

feat: can set default value and decimals

---

.github/workflows/pr.yml
.github/workflows/release.yml
CHANGELOG.md
package.json
readme.md
src/example.html
yarn.lock

- Add code coverage so it is available to view on readme
- House keeping: renamed repo to lower case so updated existing files.

chore: add code coverage to workflow

---

readme.md

Fix codecov img shield url in readme

chore: fix codecov img shield url

---

readme.md

chore: add build badge to readme

---

.github/workflows/pr.yml
.releaserc.yml
package.json
yarn.lock

This should automatically update the changelog after each release

chore: add semantic release change log to release script

---

src/components/__tests__/CurrencyInput.test.tsx
src/components/__tests__/utilities.spec.ts

Improving tests and test coverage

test: added a couple more tests

---

README.md
src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts
src/components/__tests__/CurrencyInput.test.tsx

Changed `onChange` prop to optional (raised in #36), and also tidied up README.

fix: onChange not required

---

README.md
package.json
src/components/__tests__/CurrencyInput.test.tsx
src/components/__tests__/abbrValue.spec.ts
src/components/parseAbbrValue.ts
src/components/utilities.ts
src/example.html
src/examples/Example1.tsx

Adds ability to parse abbreviated values `k`, `m` and `b`
- 1k = 1,000
- 2m = 1,000,000
- 3b = 3,000,000,000

feat: parse abbreviated values

---

.releaserc.yml

Planning to create a beta branch to test some changes and features. This is modifying the the release config slightly.

ci: modified release config for beta release

---

README.md
src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts
src/components/__tests__/CurrencyInput.test.tsx
src/components/utils/__tests__/fixedDecimalValue.spec.ts
src/components/utils/fixedDecimalValue.ts
src/components/utils/index.ts
src/examples/Example1.tsx

Allow user to specify a fixed length for decimals.
Requested from #57

feat: fixed decimal length prop

---

README.md
src/components/CurrencyInput.tsx
src/components/__tests__/CurrencyInput.test.tsx
src/components/utils/__tests__/cleanValue.spec.ts
src/components/utils/__tests__/formatValue.spec.ts
src/components/utils/__tests__/padTrimValue.spec.ts
src/components/utils/cleanValue.ts
src/components/utils/formatValue.ts
src/components/utils/padTrimValue.ts
src/components/utils/parseAbbrValue.ts

Better handling of negative values, issue #61

feat: handle negative values

---

.github/workflows/examples.yml
README.md

Add examples deployment to workflow.

ci: create examples workflow

---

src/components/utils/__tests__/cleanValue.spec.ts
src/components/utils/cleanValue.ts

Thanks to @jaykaron for pointing out a bug in the regex in #84

fix: escape prefix regex

---

src/components/__tests__/CurrencyInput-onBlurValue.spec.tsx

Added test coverage for onChange being called onBlur.

fix: add onChange to onBlur test

---

README.md
src/components/utils/__tests__/formatValue.spec.ts
src/components/utils/formatValue.ts
src/example.html
src/example.tsx
src/examples/FormatValuesExample.tsx

Export `formatValue` function and add documentation to README

feat: export format value function and add to readme

---

README.md
src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts
src/components/__tests__/CurrencyInput-handleKeyDown.spec.tsx
src/components/__tests__/CurrencyInput-maxLength.spec.tsx
src/components/__tests__/CurrencyInput.spec.tsx
src/examples/Example1.tsx
src/examples/Example2.tsx
src/examples/FormatValuesExample.tsx

Handle arrow down and arrow up step changes.

feat: handle arrow down and arrow up step changes

---

README.md
src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts
src/components/__tests__/CurrencyInput-abbreviated.spec.tsx
src/components/utils/__tests__/cleanValue.spec.ts
src/components/utils/__tests__/parseAbbrValue.spec.ts
src/components/utils/cleanValue.ts
src/components/utils/parseAbbrValue.ts

This PR:
- Adds option to turn off abbreviations,.
- Fixes bug that allowed abbreviation letter without letter 
Issue: #92

feat: can turn off abbreviations

---

src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts

Breaking Change: can pass in component ref

feat: wrap component in forwardRef

---

.github/workflows/pr.yml
README.md
package.json
src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts
src/components/__tests__/CurrencyInput-intl-config.spec.tsx
src/components/__tests__/CurrencyInput-no-locale.spec.tsx
src/components/utils/__tests__/cleanValue.spec.ts
src/components/utils/__tests__/formatValue.spec.ts
src/components/utils/__tests__/getLocaleConfig.spec.ts
src/components/utils/cleanValue.ts
src/components/utils/formatValue.ts
src/components/utils/getLocaleConfig.ts
src/components/utils/index.ts
src/examples/Example1.tsx

Add option to configure locale and currency.
Breaking Change: Using Intl.NumberFormat to format value

feat: add intl locale config option

---

src/components/utils/formatValue.ts
src/components/utils/parseAbbrValue.ts

Removed obsolete code paths to improve test coverage

test: removed obsolete code paths to improve test coverage

---

README.md

docs: add v3 release notes

---

README.md
src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts
src/components/__tests__/CurrencyInput-backspace.spec.tsx
src/components/__tests__/CurrencyInput.spec.tsx
src/components/utils/__tests__/cleanValue.spec.ts
src/components/utils/__tests__/formatValue.spec.ts
src/components/utils/formatValue.ts
src/components/utils/getSuffix.ts
src/examples/Example1.tsx
src/examples/Example3.tsx

This PR should fix some of the problems that occur when there is a suffix.

feat: handle backspace with suffix

---

src/components/CurrencyInput.tsx
src/components/__tests__/CurrencyInput-backspace.spec.tsx
src/components/__tests__/CurrencyInput-intl-config.spec.tsx
src/components/__tests__/CurrencyInput.spec.tsx
src/components/utils/__tests__/formatValue.spec.ts
src/components/utils/cleanValue.ts
src/components/utils/formatValue.ts
src/components/utils/index.ts
src/example.html
src/example.tsx
src/examples/Example3.tsx
src/examples/Example4.tsx

Added `intlConfig` to examples, and fixed a few bugs in the process.

fix: fixed a few inconsistencies and added intl config to examples

---

src/components/CurrencyInput.tsx
src/components/__tests__/CurrencyInput-backspace.spec.tsx
src/components/__tests__/CurrencyInput-fixedDecimalLength.spec.tsx
src/components/__tests__/CurrencyInput-negative.spec.tsx
src/components/__tests__/CurrencyInput.spec.tsx
src/components/utils/__tests__/formatValue.spec.ts
src/components/utils/formatValue.ts

Fix issue when initial render with decimal scale.
Issue: #117

fix: default value with decimal scale renders correctly

---

src/components/CurrencyInput.tsx
src/components/utils/__tests__/formatValue.spec.ts
src/components/utils/__tests__/padTrimValue.spec.ts
src/components/utils/formatValue.ts
src/components/utils/padTrimValue.ts

Fixes issue #120 regarding trimming decimals with `decimalScale`.

fix: formatValue trim decimalScale

---

src/components/CurrencyInput.tsx

Prevent autofocusing on load
Issue: #123

fix: prevent autofocusing on load

---

README.md
src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts
src/components/__tests__/CurrencyInput-decimals.spec.tsx
src/components/__tests__/CurrencyInput-suffix.spec.tsx
src/components/utils/__tests__/formatValue.spec.ts
src/components/utils/__tests__/getSuffix.spec.ts
src/components/utils/formatValue.ts
src/components/utils/getSuffix.ts

Allow custom suffix option.
Issue: #99

feat: allow custom suffix prop

---

src/components/CurrencyInput.tsx
src/components/__tests__/CurrencyInput-handleKeyDown.spec.tsx

Stepping up and down should not go beyond the min and max values.
Issue: #122

feat: stepping does not go beyond min max values

---

README.md

docs: correct README spelling

---

src/components/CurrencyInput.tsx

dont block controlled prop if decimal separator not present

---

package.json

fix: Allow React 18 as peer dependency

---

.github/workflows/examples.yml
.github/workflows/pr.yml
.github/workflows/release.yml
package.json
yarn.lock

- Minor version upgrade dependencies
- Update actions versions
- Use Node 18 in CI

chore: minor version upgrade dependencies and update actions versions

---

.github/workflows/codeql-analysis.yml
.github/workflows/examples.yml
.github/workflows/release.yml
.releaserc.yml
README.md
src/examples/Example1.tsx
src/examples/Example2.tsx
src/examples/Example3.tsx
src/examples/Example4.tsx
src/examples/FormatValuesExample.tsx
src/examples/index.html

I made the change to rename the default branch from `master` to `main`, and this PR updates the references to master branch in the docs and pipeline.

chore: update references to master branch to main branch

---

src/examples/Example1.tsx
src/examples/Example2.tsx
src/examples/Example3.tsx
src/examples/Example4.tsx
src/examples/FormatValuesExample.tsx
src/index.ts

Export type `CurrencyInputOnChangeValues` and update examples

fix: export type CurrencyInputOnChangeValues and update examples

---

src/index.ts

Export the 'cleanValue' function to be able to "undo" changes made by 'formatValue'

feat: export utility function 'cleanValue'

---

.github/workflows/release.yml

Include alpha branch in release run

ci: include alpha branch in release run

---

package.json

fix: Allow React 19 as peer dependency

---

.github/workflows/playwright.yml
.github/workflows/pr.yml
.github/workflows/release.yml
package.json
yarn.lock

codecov step in workflow was failing, so updating to use the github actions instead.
Also ended up updating uploader action from v3 to v4, and updating playwright test.

ci: update to use codecov action in workflow

---

.github/workflows/playwright.yml
.github/workflows/pr.yml
.github/workflows/release.yml
CHANGELOG.md
package.json
pnpm-lock.yaml
src/components/CurrencyInput.tsx
src/components/CurrencyInputProps.ts
src/components/__tests__/CurrencyInput-decimals.spec.tsx
src/components/__tests__/CurrencyInput-handleKeyDown.spec.tsx
src/components/utils/__tests__/padTrimValue.spec.ts
src/components/utils/formatValue.ts
src/components/utils/getLocaleConfig.ts
src/components/utils/padTrimValue.ts

Merging changes from main branch into alpha branch to keep it up to date.

feat: merge changes in main into alpha branch
